import logo from './logo.svg';
const storeList = [
  {
    imageSrc: logo,
    name: 'Dominos',
    address: '123 Wysteria Lane',
    city: 'Bordertown',
    state: 'MI',
    zipCode: '10100',
    category: 'Italian',
    rating: 4.5,
    reviewCount: 90,
  },
  {
    imageSrc: logo,
    name: 'Pizza Hut',
    address: '123 Wysteria Lane',
    city: 'Bordertown',
    state: 'MI',
    zipCode: '10100',
    category: 'Italian',
    rating: 4.5,
    reviewCount: 90,
  },
  {
    imageSrc: logo,
    name: 'Pizza Hut',
    address: '123 Wysteria Lane',
    city: 'Bordertown',
    state: 'MI',
    zipCode: '10100',
    category: 'Italian',
    rating: 4.5,
    reviewCount: 90,
  },
  {
    imageSrc: logo,
    name: 'Pizza Hut',
    address: '123 Wysteria Lane',
    city: 'Bordertown',
    state: 'MI',
    zipCode: '10100',
    category: 'Italian',
    rating: 4.5,
    reviewCount: 90,
  },
  {
    imageSrc: logo,
    name: 'Pizza Hut',
    address: '123 Wysteria Lane',
    city: 'Bordertown',
    state: 'MI',
    zipCode: '10100',
    category: 'Italian',
    rating: 4.5,
    reviewCount: 90,
  },
  {
    imageSrc: logo,
    name: 'Pizza Hut',
    address: '123 Wysteria Lane',
    city: 'Bordertown',
    state: 'MI',
    zipCode: '10100',
    category: 'Italian',
    rating: 4.5,
    reviewCount: 90,
  },
  {
    imageSrc: logo,
    name: 'Pizza Hut',
    address: '123 Wysteria Lane',
    city: 'Bordertown',
    state: 'MI',
    zipCode: '10100',
    category: 'Italian',
    rating: 4.5,
    reviewCount: 90,
  },
  {
    imageSrc: logo,
    name: 'Pizza Hut',
    address: '123 Wysteria Lane',
    city: 'Bordertown',
    state: 'MI',
    zipCode: '10100',
    category: 'Italian',
    rating: 4.5,
    reviewCount: 90,
  },
  {
    imageSrc: logo,
    name: 'Pizza Hut',
    address: '123 Wysteria Lane',
    city: 'Bordertown',
    state: 'MI',
    zipCode: '10100',
    category: 'Italian',
    rating: 4.5,
    reviewCount: 90,
  },
];

export default storeList;
